import React, { createContext, useContext, useState, useEffect } from 'react';

export interface NeuralBlueprint {
  product_name: string;
  mission_statement: string;
  features: string[] | { name: string; description: string }[];
  roadmap: string[] | { name: string; phase: string; description: string; goal: string }[];
  stats: {
    market_fit: number;
    complexity: string;
    scalability: string;
  };
  technical_stack?: {
    frontend: string;
    backend: string;
    database: string;
    schema: string[];
  };
  monetization?: {
    model: string;
    pricing_tiers: string[];
    gtm_strategy: string[];
  };
  design_tokens?: {
    colors: string[];
    typography: string;
  };
}

interface VaultContextType {
  savedBlueprints: NeuralBlueprint[];
  saveBlueprint: (blueprint: NeuralBlueprint) => void;
  deleteBlueprint: (name: string) => void;
  exportMarkdown: (blueprint: NeuralBlueprint) => void;
}

const VaultContext = createContext<VaultContextType | undefined>(undefined);

export const VaultProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [savedBlueprints, setSavedBlueprints] = useState<NeuralBlueprint[]>([]);

  useEffect(() => {
    const saved = localStorage.getItem('startup_architect_vault');
    if (saved) {
      try {
        setSavedBlueprints(JSON.parse(saved));
      } catch (e) {
        console.error('Failed to parse vault:', e);
      }
    }
  }, []);

  const saveBlueprint = (blueprint: NeuralBlueprint) => {
    const exists = savedBlueprints.some(b => b.product_name === blueprint.product_name);
    if (exists) return;

    const newVault = [blueprint, ...savedBlueprints];
    setSavedBlueprints(newVault);
    localStorage.setItem('startup_architect_vault', JSON.stringify(newVault));
  };

  const deleteBlueprint = (name: string) => {
    const newVault = savedBlueprints.filter(b => b.product_name !== name);
    setSavedBlueprints(newVault);
    localStorage.setItem('startup_architect_vault', JSON.stringify(newVault));
  };

  const exportMarkdown = (blueprint: NeuralBlueprint) => {
    const md = `
# ${blueprint.product_name} | Startup Blueprint
## Mission Statement
> ${blueprint.mission_statement}

## Technical DNA
- **Frontend**: ${blueprint.technical_stack?.frontend}
- **Backend**: ${blueprint.technical_stack?.backend}
- **Database**: ${blueprint.technical_stack?.database}

### Database Schema Snapshot
${blueprint.technical_stack?.schema.map(s => `- ${s}`).join('\n')}

## Monetization Strategy
- **Model**: ${blueprint.monetization?.model}
- **Pricing Tiers**: ${blueprint.monetization?.pricing_tiers.join(', ')}
- **GTM Strategy**:
${blueprint.monetization?.gtm_strategy.map(s => `- ${s}`).join('\n')}

## Design Tokens
- **Colors**: ${blueprint.design_tokens?.colors.join(', ')}
- **Typography**: ${blueprint.design_tokens?.typography}

## Core Features
${blueprint.features.map(f => `- **${typeof f === 'object' ? f.name : f}**: ${typeof f === 'object' ? f.description : ''}`).join('\n')}

## Execution Roadmap
${blueprint.roadmap.map((r, i) => `- **Phase ${i + 1}**: ${typeof r === 'object' ? r.description || r.goal : r}`).join('\n')}

---
Generated by Prompt-BooK Neural Core v4.0.2
    `;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${blueprint.product_name.replace(/\s+/g, '_')}_blueprint.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <VaultContext.Provider value={{ savedBlueprints, saveBlueprint, deleteBlueprint, exportMarkdown }}>
      {children}
    </VaultContext.Provider>
  );
};

export const useVault = () => {
  const context = useContext(VaultContext);
  if (!context) throw new Error('useVault must be used within a VaultProvider');
  return context;
};
